// <auto-generated />
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage;
using Microsoft.EntityFrameworkCore.Storage.Internal;
using MVCWebApi.DataAccessLayer;
using System;

namespace MVCWebApi.Migrations
{
    [DbContext(typeof(LibraryContext))]
    [Migration("20171114142200_Init")]
    partial class Init
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "2.0.0-rtm-26452")
                .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

            modelBuilder.Entity("MVCWebApi.Models.Adress", b =>
                {
                    b.Property<int>("AdressId")
                        .ValueGeneratedOnAdd();

                    b.Property<string>("City");

                    b.Property<int?>("ClientId");

                    b.Property<string>("Country");

                    b.Property<int>("FlatNumber");

                    b.Property<int>("HouseNumber");

                    b.Property<int>("PostalCode");

                    b.Property<string>("Street");

                    b.HasKey("AdressId");

                    b.HasIndex("ClientId");

                    b.ToTable("Adresses");
                });

            modelBuilder.Entity("MVCWebApi.Models.Author", b =>
                {
                    b.Property<int>("AuthorId")
                        .ValueGeneratedOnAdd();

                    b.Property<DateTime>("Birthday");

                    b.Property<string>("LastName");

                    b.Property<string>("Name");

                    b.HasKey("AuthorId");

                    b.ToTable("Authors");
                });

            modelBuilder.Entity("MVCWebApi.Models.Client", b =>
                {
                    b.Property<int>("ClientId")
                        .ValueGeneratedOnAdd();

                    b.Property<int>("AdressId");

                    b.Property<int>("ContactId");

                    b.Property<string>("LastName");

                    b.Property<string>("Name");

                    b.Property<string>("Password");

                    b.Property<string>("Username");

                    b.HasKey("ClientId");

                    b.ToTable("Client");
                });

            modelBuilder.Entity("MVCWebApi.Models.Contact", b =>
                {
                    b.Property<int>("ContactId")
                        .ValueGeneratedOnAdd();

                    b.Property<int?>("ClientId");

                    b.Property<string>("Email");

                    b.Property<int>("PhoneNumber1");

                    b.Property<int>("PhoneNumber2");

                    b.HasKey("ContactId");

                    b.HasIndex("ClientId");

                    b.ToTable("Contact");
                });

            modelBuilder.Entity("MVCWebApi.Models.Order", b =>
                {
                    b.Property<int>("OrderId")
                        .ValueGeneratedOnAdd();

                    b.Property<int>("ClientId");

                    b.Property<DateTime>("RealizationDate");

                    b.Property<DateTime>("SubmitDate");

                    b.HasKey("OrderId");

                    b.HasIndex("ClientId");

                    b.ToTable("Order");
                });

            modelBuilder.Entity("MVCWebApi.Models.Adress", b =>
                {
                    b.HasOne("MVCWebApi.Models.Client", "Client")
                        .WithMany("Adresses")
                        .HasForeignKey("ClientId");
                });

            modelBuilder.Entity("MVCWebApi.Models.Contact", b =>
                {
                    b.HasOne("MVCWebApi.Models.Client", "Client")
                        .WithMany("Contcats")
                        .HasForeignKey("ClientId");
                });

            modelBuilder.Entity("MVCWebApi.Models.Order", b =>
                {
                    b.HasOne("MVCWebApi.Models.Client", "Client")
                        .WithMany("Orders")
                        .HasForeignKey("ClientId")
                        .OnDelete(DeleteBehavior.Cascade);
                });
#pragma warning restore 612, 618
        }
    }
}
